version: '1.0'
services:

  redis:
    image: redis
    container_name: 'some-redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 32768:6379


  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8084:8084



  postgres_db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: 'postgres'
    environment:
        POSTGRES_DB: 'clientprofile'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'damuhe65'
    ports:
          - "5432:5432"
    restart: unless-stopped

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"
